/**
 * @file stream.hpp
 * @brief Authenticated streaming encryption using XChaCha20-Poly1305.
 *
 * Provides `Encryptor` and `Decryptor` classes for streaming authenticated
 * encryption over `crypto_secretstream_xchacha20poly1305` (libsodium).
 *
 * Streaming encryption is ideal for large files or data that cannot fit
 * entirely in memory. The plaintext is split into chunks, each independently
 * authenticated with a Poly1305 MAC, and linked together so that reordering,
 * truncation, or chunk removal is detected.
 *
 * @par Stream file layout:
 * @code
 * [ header (24 bytes) | chunk_1 | chunk_2 | ... | chunk_N (TAG_FINAL) ]
 * @endcode
 * The header is generated by the `Encryptor` constructor and must be
 * transmitted to the `Decryptor` before any chunk is pulled.
 *
 * @par Chunk layout (each chunk):
 * @code
 * [ MAC (17 bytes, includes tag) | ciphertext (plaintext_size bytes) ]
 * @endcode
 * Overhead per chunk: `crypto_secretstream_xchacha20poly1305_ABYTES` (17 bytes).
 *
 * @par Typical usage:
 * @code
 *     // ── Encryption ────────────────────────────────────────────
 *     sylvite::symmetric::stream::XChaCha20Poly1305Stream::Encryptor enc(key);
 *     write_to_file(enc.header());                // transmit header first
 *     while (has_more_data()) {
 *         auto ct = enc.update(read_chunk());     // intermediate chunks
 *         write_to_file(ct);
 *     }
 *     write_to_file(enc.finalize(last_chunk));    // final chunk (TAG_FINAL)
 *
 *     // ── Decryption ────────────────────────────────────────────
 *     sylvite::symmetric::stream::XChaCha20Poly1305Stream::Decryptor dec(key, header);
 *     while (has_more_data()) {
 *         auto [plain, tag] = dec.pull(read_chunk());
 *         write_to_file(plain);
 *         if (tag == crypto_secretstream_xchacha20poly1305_TAG_FINAL) break;
 *     }
 * @endcode
 *
 * @par Security properties:
 *  - Confidentiality:   XChaCha20 (256-bit key, 192-bit nonce)
 *  - Authentication:    Poly1305 MAC per chunk
 *  - Stream integrity:  Chunk reordering, removal, and truncation are detected
 *  - Nonce management:  Handled internally by libsodium — never reused
 *
 * @par Thread safety:
 *  `Encryptor` and `Decryptor` are NOT thread-safe. Each instance must be
 *  used from a single thread. Create separate instances per thread.
 */

#ifndef SYLVITE_SYMMETRIC_STREAM_HPP
#define SYLVITE_SYMMETRIC_STREAM_HPP

#include "../frsdef.hpp"
#include <sodium.h>
#include "../concepts.hpp"
#include "../internal/base.hpp"
#include "../internal/noncemodify.hpp"
#include "../types/nonce.hpp"
#include "../types/streamheader.hpp"

namespace sylvite::symmetric::stream {
namespace XChaCha20Poly1305Stream {

// ─────────────────────────────────────────────────────────────────
//  PullResult — returned by Decryptor::pull()
// ─────────────────────────────────────────────────────────────────

/**
 * @brief Result of a single Decryptor::pull() call.
 *
 * Contains the decrypted plaintext for the chunk and the tag that
 * libsodium attached to it during encryption. Inspect `tag` to detect
 * the end of the stream (`TAG_FINAL`) or re-keying events (`TAG_REKEY`).
 *
 * @par Common tag values:
 *  - `crypto_secretstream_xchacha20poly1305_TAG_MESSAGE` — regular chunk
 *  - `crypto_secretstream_xchacha20poly1305_TAG_FINAL`   — last chunk,
 *    stream is complete. No more chunks should follow.
 *  - `crypto_secretstream_xchacha20poly1305_TAG_REKEY`   — rekeying event,
 *    forward secrecy boundary. Decryption continues normally.
 *  - `crypto_secretstream_xchacha20poly1305_TAG_PUSH`    — flush boundary
 *    (intermediate finalization hint for the application layer).
 */
struct PullResult {
    /// Decrypted plaintext for this chunk.
    std::vector<std::uint8_t> plaintext;

    /// Tag attached to this chunk by the Encryptor.
    std::uint8_t tag = 0;
};

// ─────────────────────────────────────────────────────────────────
//  Encryptor
// ─────────────────────────────────────────────────────────────────

/**
 * @brief Streaming encryptor for XChaCha20-Poly1305.
 *
 * Wraps `crypto_secretstream_xchacha20poly1305_push`. Each call to
 * `update()` produces an independently authenticated ciphertext chunk.
 * `finalize()` emits the last chunk tagged with `TAG_FINAL`, signaling
 * the end of the stream to the `Decryptor`.
 *
 * @par Lifecycle:
 *  1. Construct with a 32-byte key → header is generated automatically.
 *  2. Call `header()` and transmit it to the receiver before any chunk.
 *  3. Call `update()` for each intermediate chunk.
 *  4. Call `finalize()` exactly once with the last chunk.
 *  5. After `finalize()`, the Encryptor is sealed — further calls throw.
 *
 * @note `Encryptor` is move-only (`NonCopyable`). The internal libsodium
 *       state must not be duplicated — copying would produce two streams
 *       sharing the same state, leading to nonce reuse.
 */
class Encryptor final : public sylvite::internal::NonCopyable {

    sylvite::types::StreamHeader h_;
    crypto_secretstream_xchacha20poly1305_state state_;
    bool finalized_ = false;

public:

    /**
     * @brief Constructs an Encryptor and initializes the stream.
     *
     * Calls `crypto_secretstream_xchacha20poly1305_init_push` internally,
     * which generates the stream header and writes it into `h_`. The header
     * must be retrieved via `header()` and transmitted to the Decryptor
     * before sending any encrypted chunk.
     *
     * @param key_  Symmetric key of exactly
     *              `crypto_secretstream_xchacha20poly1305_KEYBYTES` (32) bytes.
     *
     * @throws sylvite::exceptions::SodiumLogicError  If the key size is wrong.
     *
     * @par Example:
     * @code
     *     sylvite::types::Key key(crypto_secretstream_xchacha20poly1305_KEYBYTES);
     *     key.random_generate();
     *     sylvite::symmetric::stream::XChaCha20Poly1305Stream::Encryptor enc(key);
     *     send(enc.header());  // must be sent before any chunk
     * @endcode
     */
    explicit Encryptor(const sylvite::types::Key& key_) {
        if (key_.size() != crypto_secretstream_xchacha20poly1305_KEYBYTES)
            throw sylvite::exceptions::SodiumLogicError(
                "Key too short for XChaCha20Poly1305Stream: expected " +
                std::to_string(crypto_secretstream_xchacha20poly1305_KEYBYTES) +
                " bytes, got " + std::to_string(key_.size()) + "."
            );
        crypto_secretstream_xchacha20poly1305_init_push(
            &state_, h_.data(), key_.data());
    }

    /**
     * @brief Returns the stream header generated during construction.
     *
     * The header contains the nonce and state needed by the Decryptor to
     * initialize its pull state. It must be transmitted to the receiver
     * **before** any encrypted chunk — order matters.
     *
     * @return  Const reference to the internal `StreamHeader`
     *          (`crypto_secretstream_xchacha20poly1305_HEADERBYTES` = 24 bytes).
     *
     * @note    The header is not secret — it can be sent in the clear.
     *          It does not need to be authenticated separately; libsodium
     *          binds it to the stream state internally.
     */
    [[nodiscard]]
    const sylvite::types::StreamHeader& header() const noexcept { return h_; }

    /**
     * @brief Encrypts a chunk and returns the authenticated ciphertext.
     *
     * Produces a ciphertext of `data_.size() +
     * crypto_secretstream_xchacha20poly1305_ABYTES` bytes. The chunk is
     * tagged with `TAG_MESSAGE`, meaning it is an intermediate chunk and
     * more data will follow.
     *
     * @tparam T  Any contiguous byte container (std::vector<uint8_t>,
     *            std::span<uint8_t>, std::string, etc.).
     * @param  data_  Plaintext chunk to encrypt. May be empty.
     * @return        Authenticated ciphertext chunk.
     *
     * @throws sylvite::exceptions::SodiumLogicError    If called after
     *         `finalize()`.
     * @throws sylvite::exceptions::SodiumRuntimeError  If libsodium push
     *         fails (should not happen under normal conditions).
     *
     * @par Example:
     * @code
     *     while (has_data()) {
     *         auto ct = enc.update(read_chunk(CHUNK_SIZE));
     *         write(ct);
     *     }
     * @endcode
     */
    template<sylvite::concepts::ContiguousByteContainer T>
    [[nodiscard]]
    sylvite::types::CipherText update(const T& data_) {
        if (finalized_) throw sylvite::exceptions::SodiumLogicError(
            "Cannot push to a finalized XChaCha20Poly1305Stream.");
        sylvite::types::CipherText ct_(
            data_.size() + crypto_secretstream_xchacha20poly1305_ABYTES);
        unsigned long long written_;
        if (crypto_secretstream_xchacha20poly1305_push(
                &state_, ct_.data(), &written_,
                reinterpret_cast<const unsigned char*>(data_.data()), data_.size(),
                nullptr, 0,
                crypto_secretstream_xchacha20poly1305_TAG_MESSAGE) != 0)
            throw sylvite::exceptions::SodiumRuntimeError(
                "XChaCha20Poly1305Stream update failed.");
        return ct_;
    }

    /**
     * @brief Encrypts the last chunk, finalizes the stream, and seals the Encryptor.
     *
     * Tags the chunk with `TAG_FINAL`. After this call, the Encryptor is
     * sealed and any further call to `update()` or `finalize()` will throw.
     * The Decryptor will detect `TAG_FINAL` via `pull()` and know the stream
     * is complete — any data after this chunk should be rejected.
     *
     * @tparam T  Any contiguous byte container.
     * @param  data_  Last plaintext chunk to encrypt. May be empty (to emit
     *                a zero-length final chunk that just signals end-of-stream).
     * @return        Authenticated ciphertext chunk tagged with TAG_FINAL.
     *
     * @throws sylvite::exceptions::SodiumLogicError    If the stream was
     *         already finalized.
     * @throws sylvite::exceptions::SodiumRuntimeError  If libsodium push fails.
     *
     * @par Example:
     * @code
     *     // Finalize with remaining data
     *     write(enc.finalize(last_chunk));
     *
     *     // Finalize with no remaining data (just signals end-of-stream)
     *     write(enc.finalize(std::span<const uint8_t>{}));
     * @endcode
     */
    template<sylvite::concepts::ContiguousByteContainer T>
    [[nodiscard]]
    sylvite::types::CipherText finalize(const T& data_) {
        if (finalized_) throw sylvite::exceptions::SodiumLogicError(
            "XChaCha20Poly1305Stream already finalized.");
        sylvite::types::CipherText ct_(
            data_.size() + crypto_secretstream_xchacha20poly1305_ABYTES);
        unsigned long long written_;
        if (crypto_secretstream_xchacha20poly1305_push(
                &state_, ct_.data(), &written_,
                reinterpret_cast<const unsigned char*>(data_.data()), data_.size(),
                nullptr, 0,
                crypto_secretstream_xchacha20poly1305_TAG_FINAL) != 0)
            throw sylvite::exceptions::SodiumRuntimeError(
                "XChaCha20Poly1305Stream finalize failed.");
        finalized_ = true;
        return ct_;
    }

    /**
     * @brief Returns true if `finalize()` has been called.
     *
     * A finalized Encryptor cannot push more data. Use this to guard
     * against accidental reuse after finalization.
     */
    [[nodiscard]] bool finalized() const noexcept { return finalized_; }
};


// ─────────────────────────────────────────────────────────────────
//  Decryptor
// ─────────────────────────────────────────────────────────────────

/**
 * @brief Streaming decryptor for XChaCha20-Poly1305.
 *
 * Wraps `crypto_secretstream_xchacha20poly1305_pull`. Each call to
 * `pull()` decrypts and authenticates one ciphertext chunk produced
 * by a matching `Encryptor`. Chunks must be pulled in the same order
 * they were pushed — libsodium detects any reordering or omission.
 *
 * @par Lifecycle:
 *  1. Construct with the same 32-byte key and the stream header received
 *     from the Encryptor.
 *  2. Call `pull()` for each ciphertext chunk in order.
 *  3. Stop when `pull()` returns a `PullResult` with
 *     `tag == TAG_FINAL`.
 *  4. After `TAG_FINAL`, the stream is complete. Further `pull()` calls
 *     throw `SodiumLogicError`.
 *
 * @note `Decryptor` is move-only (`NonCopyable`). Copying the internal
 *       libsodium state would allow replaying the same stream from an
 *       intermediate point, which is a security hazard.
 */
class Decryptor final : public sylvite::internal::NonCopyable {

    crypto_secretstream_xchacha20poly1305_state state_;
    bool finalized_ = false;

public:

    /**
     * @brief Constructs a Decryptor and initializes the pull state.
     *
     * Calls `crypto_secretstream_xchacha20poly1305_init_pull` with the
     * provided key and stream header. The header must be the one returned
     * by the matching `Encryptor::header()` — using a mismatched header
     * will cause all subsequent `pull()` calls to fail authentication.
     *
     * @param key_     Same key used by the Encryptor. Must be exactly
     *                 `crypto_secretstream_xchacha20poly1305_KEYBYTES` (32) bytes.
     * @param header_  Stream header produced by the Encryptor.
     *                 Must be exactly
     *                 `crypto_secretstream_xchacha20poly1305_HEADERBYTES` (24) bytes.
     *
     * @throws sylvite::exceptions::SodiumLogicError  If the key size is wrong.
     * @throws sylvite::exceptions::SodiumRuntimeError  If libsodium init fails.
     *
     * @par Example:
     * @code
     *     sylvite::types::StreamHeader hdr(received_header_bytes);
     *     sylvite::symmetric::stream::XChaCha20Poly1305Stream::Decryptor dec(key, hdr);
     * @endcode
     */
    explicit Decryptor(
        const sylvite::types::Key& key_,
        const sylvite::types::StreamHeader& header_
    ) {
        if (key_.size() != crypto_secretstream_xchacha20poly1305_KEYBYTES)
            throw sylvite::exceptions::SodiumLogicError(
                "Key too short for XChaCha20Poly1305Stream decryption: expected " +
                std::to_string(crypto_secretstream_xchacha20poly1305_KEYBYTES) +
                " bytes, got " + std::to_string(key_.size()) + "."
            );
        if (crypto_secretstream_xchacha20poly1305_init_pull(
                &state_, header_.data(), key_.data()) != 0)
            throw sylvite::exceptions::SodiumRuntimeError(
                "XChaCha20Poly1305Stream Decryptor init failed.");
    }

    /**
     * @brief Decrypts and authenticates one ciphertext chunk.
     *
     * The ciphertext must have been produced by `Encryptor::update()` or
     * `Encryptor::finalize()` with the matching key. Chunks must be pulled
     * in the exact same order they were pushed.
     *
     * @param ciphertext_  Encrypted chunk. Size must be at least
     *                     `crypto_secretstream_xchacha20poly1305_ABYTES` bytes.
     * @return             `PullResult` containing the plaintext and the tag
     *                     attached by the Encryptor.
     *
     * @throws sylvite::exceptions::SodiumLogicError       If the stream has
     *         already received `TAG_FINAL` (stream is complete).
     * @throws sylvite::exceptions::SodiumInvalidSignature If authentication
     *         fails — chunk is corrupted, reordered, truncated, or the key
     *         or header is wrong.
     *
     * @par Checking for end-of-stream:
     * @code
     *     auto [plain, tag] = dec.pull(ct_chunk);
     *     out.write(...plain...);
     *     if (tag == crypto_secretstream_xchacha20poly1305_TAG_FINAL) {
     *         // stream is complete — stop pulling
     *     }
     * @endcode
     *
     * @par Security note:
     *     Never write plaintext to disk or network before `pull()` returns
     *     successfully — the MAC is verified before any plaintext is returned,
     *     so partial/unauthenticated data is never exposed to the caller.
     */
    [[nodiscard]]
    PullResult pull(std::span<const std::uint8_t> ciphertext_) {
        if (finalized_) throw sylvite::exceptions::SodiumLogicError(
            "Cannot pull from a finalized XChaCha20Poly1305Stream: "
            "TAG_FINAL was already received.");

        if (ciphertext_.size() < crypto_secretstream_xchacha20poly1305_ABYTES)
            throw sylvite::exceptions::SodiumLogicError(
                "Ciphertext chunk too short for XChaCha20Poly1305Stream: "
                "minimum size is " +
                std::to_string(crypto_secretstream_xchacha20poly1305_ABYTES) +
                " bytes, got " + std::to_string(ciphertext_.size()) + ".");

        PullResult result;
        result.plaintext.resize(
            ciphertext_.size() - crypto_secretstream_xchacha20poly1305_ABYTES);

        unsigned long long plain_len_;
        if (crypto_secretstream_xchacha20poly1305_pull(
                &state_,
                result.plaintext.data(), &plain_len_,
                &result.tag,
                ciphertext_.data(), ciphertext_.size(),
                nullptr, 0) != 0)
            throw sylvite::exceptions::SodiumInvalidSignature(
                "XChaCha20Poly1305Stream authentication failed: chunk is "
                "corrupted, reordered, or the key/header is incorrect.");

        result.plaintext.resize(static_cast<std::size_t>(plain_len_));

        if (result.tag == crypto_secretstream_xchacha20poly1305_TAG_FINAL)
            finalized_ = true;

        return result;
    }

    /**
     * @brief Returns true if `TAG_FINAL` has been received.
     *
     * After this returns true, the stream is complete and `pull()` will
     * throw on any further call. Use this to assert stream completeness
     * after the read loop.
     */
    [[nodiscard]] bool finalized() const noexcept { return finalized_; }
};

} // namespace XChaCha20Poly1305Stream
} // namespace sylvite::symmetric::stream

#endif // SYLVITE_SYMMETRIC_STREAM_HPP
